apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-chart.fullname" . }}
  labels:
    {{- include "java-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service_app.type }}
  ports:
    - port: {{ .Values.service_app.port }}
      targetPort: java-app-port
      protocol: TCP
      name: java-app-port
  selector:
    app.kubernetes.io/type: "java-app"
    {{- include "java-chart.selectorLabels" . | nindent 4 }}
