apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:
  #add from a forum      
  # storageClassName: managed-nfs-storage      
  ###
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs
    path: /nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
spec:
  volumeName: pv-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
