apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    run: db
spec:
  volumes:
    - name: storage-db
      persistentVolumeClaim:
        claimName: pvc-local
  containers:
    - name: db
      image: repo.local/db:v1
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: storage-db
          mountPath: "/var/lib/mysql"
         
