apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: repo.local/app:2
          ports:
          - name: app-port
            containerPort: 8080
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: 200m    
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - port: 8080
    targetPort: app-port
    protocol: TCP
  selector:
    app: app
  type: ClusterIP
