apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    run: app
spec:
  volumes:
    - name: storage-app
      persistentVolumeClaim:
        claimName: pvc-nfs
  containers:
    - name: app
      image: repo.local/app:v1
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: storage-app
          mountPath: "/usr/local/tomcat/webapps"
         
